// rabadon-truth — what does THIS repo already know how to check? C++17, zero deps.
//
// The always-on net is supposed to run "the project's existing truths" after a
// tool call. Measured on this machine before writing a line of this file: of 66
// project folders, 38 contain code, and only 6 of those have any test suite.
// A net that only knows how to run a test suite is therefore dead in ~5 out of 6
// real repositories — including most of the ones an autonomous agent is turned
// loose on. So the net does not ask "where are your tests"; it asks "what is the
// strongest thing you already have that can be RUN and can come back red".
//
// The ladder, strongest first. Each rung is a real command, discovered from real
// files, and NOTHING here calls a model:
//   1 SUITE   the project's own test suite            (it can fail for behaviour)
//   2 BUILD   compile / typecheck                     (it can fail for meaning)
//   3 SYNTAX  parse every source file                 (it can fail for form)
//   0 NONE    nothing runnable was found              (say so; never pretend)
//
// The rung is recorded with the verdict, always. "Proven by your test suite" and
// "it still compiles" are not the same claim, and a ledger that blurs them is
// worth nothing. This is also the honest answer to a hostile reviewer: rabadon
// grades its own evidence, out loud, and a weak rung is reported as weak.
//
// Usage: rabadon-truth [dir] [--json]
//   exit 0 = a runnable truth was found   exit 1 = none (dir has no checkable truth)

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <regex>
#include <dirent.h>
#include <sys/stat.h>
#include "cli_help.h"

using std::string;
using std::vector;

static string read_file(const string& p) {
  std::ifstream f(p, std::ios::binary);
  if (!f) return "";
  std::stringstream ss; ss << f.rdbuf(); return ss.str();
}
static bool exists(const string& p) { struct stat sb; return stat(p.c_str(), &sb) == 0; }
static bool is_dir(const string& p) { struct stat sb; return stat(p.c_str(), &sb) == 0 && S_ISDIR(sb.st_mode); }

static vector<string> list_dir(const string& d) {
  vector<string> out;
  DIR* dp = opendir(d.c_str());
  if (!dp) return out;
  while (struct dirent* e = readdir(dp)) {
    string n = e->d_name;
    if (n == "." || n == "..") continue;
    out.push_back(n);
  }
  closedir(dp);
  std::sort(out.begin(), out.end());
  return out;
}

// noise that is never the project's own source
static bool skip_dir(const string& n) {
  static const char* junk[] = {"node_modules", ".git", "build", "dist", ".next", "venv",
                               ".venv", "__pycache__", "target", "vendor", "Pods",
                               "DerivedData", ".rabadon", "coverage", ".cache"};
  for (const char* j : junk) if (n == j) return true;
  return n.size() > 1 && n[0] == '.';
}

static string ext_of(const string& n) {
  size_t d = n.rfind('.');
  return d == string::npos ? "" : n.substr(d);
}

// Can this file be the check that caught a bug?
//
// The question the lock asks is not "what language is this" — asking that is
// what left redis's 229 .tcl files, rails's 1290 *_test.rb and discourse's 3373
// *_spec.rb with nothing holding them, because none of those extensions was on
// a list. It is "if a fix rewrote this file, would the suite stop being able to
// come back red?" A .tcl case, a .conf a test server boots with and an expected
// output in a .txt all answer yes whatever they are written in.
//
// Three kinds answer no, and each one costs something real if locked. A build
// artifact is regenerated by an honest build, so locking redis's tests/*.so
// refuses `make`. A document under test/ is read by a person, never by the
// runner, so locking test/README.md refuses an honest doc edit and buys no
// protection. A dotfile there is configuration of the same kind.
static bool can_be_a_check(const string& n, const string& e) {
  if (!n.empty() && n[0] == '.') return false;            // .gitignore, .env
  static const char* artifact[] = {
      ".so", ".dylib", ".dll", ".o", ".a", ".lib", ".exe", ".bin", ".class",
      ".jar", ".wasm", ".pyc", ".pyo", ".rdb", ".zip", ".gz", ".tgz", ".tar",
      ".bz2", ".xz", ".7z", ".png", ".jpg", ".jpeg", ".gif", ".ico", ".pdf",
      ".mp4", ".mov", ".mp3", ".wav", ".woff", ".woff2", ".ttf", ".eot", ".otf"};
  for (const char* a : artifact) if (e == a) return false;
  static const char* document[] = {".md", ".markdown", ".rst", ".adoc"};
  for (const char* d : document) if (e == d) return false;
  return true;
}

// count source files by language, and remember which top-level dirs hold them
struct Scan {
  int js = 0, ts = 0, py = 0, cpp = 0, go = 0, rs = 0, swift = 0, java = 0;
  vector<string> codeDirs;
  vector<string> testFiles;
  vector<std::regex> guardTestRx;   // guard.json testPaths — the project's own law
  // Three bounds used to stop this walk without a word, and every one of them
  // came out of a real repo. A cap nobody is told about is how repair's lock
  // list stopped at 32 and a foreign repo went through as VERIFIED. They are
  // still bounds — this runs inside a hook — but they announce themselves now,
  // and `discoveryCapped` rides in the JSON so repair can say it out loud too.
  bool cappedDepth = false, cappedBudget = false, cappedList = false;
  // Files whose whole name is `test` or `spec`. Held back rather than locked,
  // because ONE of them is not a convention and locking it is an outage: jinja
  // has src/jinja2/tests.py, which is source (the `is defined` tests the
  // template language exposes), and examples/basic/test.py, which is an
  // example. date-fns has 253 of them, one beside each function, and that IS
  // the convention. So they are promoted only when the repo repeats itself.
  vector<string> stemCandidates;
  int total() const { return js + ts + py + cpp + go + rs + swift + java; }
  string capped() const {
    string out;
    if (cappedDepth)  out += out.empty() ? "depth"  : ",depth";
    if (cappedBudget) out += out.empty() ? "budget" : ",budget";
    if (cappedList)   out += out.empty() ? "limit"  : ",limit";
    return out;
  }
};

// How deep the walk goes, how many entries it may touch, and how many test
// files it may name. The first was 4 and colinhacks/zod keeps its suite at
// packages/zod/src/v4/classic/tests, six down, so 170 test files were on disk
// and 2 were discovered. The list cap was 512 and the budget 20000; both are
// higher now and all three say so when they bite.
static const int kMaxDepth = 12;
static const int kMaxEntries = 200000;
static const size_t kMaxTestFiles = 4096;

// guard.json's testPaths are authored per-project (LLM or hand); when they
// exist they beat any heuristic — express keeps its suite in test/*.js, which
// no test_*/tests/ pattern sees. Caught live in the wild, 31.07: an empty
// testFiles list meant ZERO hash locks, and a test-neutering fake fix sailed
// through repair as VERIFIED.
static void load_guard_test_rx(const string& dir, Scan& s) {
  const string g = read_file(dir + "/.rabadon/guard.json");
  if (g.empty()) return;
  size_t k = g.find("\"testPaths\"");
  if (k == string::npos) return;
  size_t a = g.find('[', k), b = g.find(']', a);
  if (a == string::npos || b == string::npos) return;
  size_t i = a;
  while (i < b) {
    size_t q = g.find('"', i + 1);
    if (q == string::npos || q >= b) break;
    string pat; size_t j = q + 1;
    for (; j < b; j++) {
      if (g[j] == '\\' && j + 1 < b) { pat += g[j + 1]; j++; continue; }  // JSON unescape
      if (g[j] == '"') break;
      pat += g[j];
    }
    try { s.guardTestRx.emplace_back(pat, std::regex::ECMAScript | std::regex::icase); }
    catch (...) { /* a broken pattern must not kill discovery */ }
    i = j;
  }
}

static void scan_into(const string& dir, const string& rel, Scan& s, int depth, int& budget) {
  if (depth > kMaxDepth) { s.cappedDepth = true; return; }
  if (budget <= 0) { s.cappedBudget = true; return; }
  for (const string& n : list_dir(dir)) {
    if (budget-- <= 0) { s.cappedBudget = true; return; }
    const string full = dir + "/" + n;
    const string r = rel.empty() ? n : rel + "/" + n;
    if (is_dir(full)) {
      if (skip_dir(n)) continue;
      scan_into(full, r, s, depth + 1, budget);
      continue;
    }
    const string e = ext_of(n);
    bool code = true;
    if (e == ".js" || e == ".jsx" || e == ".mjs" || e == ".cjs") s.js++;
    else if (e == ".ts" || e == ".tsx") s.ts++;
    else if (e == ".py") s.py++;
    else if (e == ".cpp" || e == ".cc" || e == ".c" || e == ".h" || e == ".hpp") s.cpp++;
    else if (e == ".go") s.go++;
    else if (e == ".rs") s.rs++;
    else if (e == ".swift") s.swift++;
    else if (e == ".java") s.java++;
    else code = false;
    if (code) {
      // remember the top-level directory this code lives in
      size_t slash = r.find('/');
      const string top = slash == string::npos ? string(".") : r.substr(0, slash);
      if (std::find(s.codeDirs.begin(), s.codeDirs.end(), top) == s.codeDirs.end())
        s.codeDirs.push_back(top);
    }
    // Everything below runs for EVERY file, whatever language it is written in.
    // It used to sit under `if (!code) continue;`, which meant the location rule
    // eleven lines down — a file under tests/ belongs to the suite — never ran
    // for a language nobody had listed. redis locked 255 files that way and not
    // one of them was a redis test: they were C headers named test_hooks.h from
    // deps/jemalloc, a vendored dependency, while the 229 .tcl files that ARE
    // the suite fell through at the extension check.
    if (!can_be_a_check(n, e)) continue;
    // a test file is one the arbiter must later LOCK, so a fix cannot be faked
    // by weakening the check that caught it
    // The BASENAME with its extension removed, because date-fns/date-fns names
    // every one of its 253 test files `test.ts` and puts it beside the function
    // it tests (src/addDays/test.ts). No pattern here saw a single one of them:
    // the name matches nothing and the path matches nothing. Comparing the whole
    // stem rather than searching for the word is what keeps `contest.ts` and a
    // directory called `latest` out of the lock, and a source file read as a
    // test is a source file a fix may not touch.
    const string stem = e.empty() ? n : n.substr(0, n.size() - e.size());
    bool looksTest =
        n.rfind("test_", 0) == 0 || n.find("_test.") != string::npos ||
        n.find(".test.") != string::npos || n.find(".spec.") != string::npos ||
        // `_spec.` is rspec's whole convention and it was not here. discourse
        // names 3373 files that way and matched on neither the name nor the
        // path, because `spec/` was not a test directory either.
        n.find("_spec.") != string::npos ||
        r.rfind("test/", 0) == 0 || r.find("/test/") != string::npos ||
        r.rfind("tests/", 0) == 0 || r.find("/tests/") != string::npos ||
        r.rfind("spec/", 0) == 0 || r.find("/spec/") != string::npos ||
        r.find("__tests__/") != string::npos || r.find("__test__/") != string::npos;
    // `tests` is deliberately not here. A module called tests.py is ordinarily
    // source, and jinja's is: locking it would refuse a fix to the language's
    // own test functions as if it were tampering with a suite.
    if (!looksTest && (stem == "test" || stem == "spec")) {
      s.stemCandidates.push_back(r);
      continue;
    }
    if (!looksTest)
      for (const auto& rx : s.guardTestRx)
        if (std::regex_search(r, rx)) { looksTest = true; break; }
    if (!looksTest) continue;
    if (s.testFiles.size() >= kMaxTestFiles) { s.cappedList = true; continue; }
    s.testFiles.push_back(r);
  }
}

// a package.json script, without a JSON parser: find "key" inside "scripts"
static string npm_script(const string& pkg, const string& key) {
  size_t sc = pkg.find("\"scripts\"");
  if (sc == string::npos) return "";
  size_t brace = pkg.find('{', sc);
  if (brace == string::npos) return "";
  int depth = 0; size_t end = brace;
  for (size_t i = brace; i < pkg.size(); i++) {
    if (pkg[i] == '{') depth++;
    else if (pkg[i] == '}') { depth--; if (!depth) { end = i; break; } }
  }
  const string block = pkg.substr(brace, end - brace + 1);
  const string pat = "\"" + key + "\"";
  size_t k = block.find(pat);
  if (k == string::npos) return "";
  size_t c = block.find(':', k + pat.size());
  if (c == string::npos) return "";
  size_t q = block.find('"', c);
  if (q == string::npos) return "";
  string v;
  for (size_t i = q + 1; i < block.size(); i++) {
    if (block[i] == '\\' && i + 1 < block.size()) { v += block[++i]; continue; }
    if (block[i] == '"') break;
    v += block[i];
  }
  return v;
}

static bool make_has_target(const string& mk, const string& target) {
  size_t pos = 0;
  const string pat = target + ":";
  while ((pos = mk.find(pat, pos)) != string::npos) {
    if (pos == 0 || mk[pos - 1] == '\n') return true;
    pos += pat.size();
  }
  return false;
}

struct Truth {
  int level = 0;                 // 3 suite, 2 build, 1 syntax, 0 none (higher is stronger)
  string kind = "none";
  string run;                    // the actual command
  string why;                    // the file that proved it exists
};

// "check" in .rabadon/guard.json, authored by the user. Deliberately NOT a
// separate file: guard.json is the one thing in .rabadon the gate already
// refuses to let a supervised session weaken, and a check command living
// anywhere else is a check command the agent can quietly point at `true`.
static string declared_check(const string& dir) {
  const string g = read_file(dir + "/.rabadon/guard.json");
  size_t k = g.find("\"check\"");
  if (k == string::npos) return "";
  size_t c = g.find(':', k + 7);
  if (c == string::npos) return "";
  size_t q = g.find('"', c);
  if (q == string::npos) return "";
  string v;
  for (size_t i = q + 1; i < g.size(); i++) {
    if (g[i] == '\\' && i + 1 < g.size()) { v += g[++i]; continue; }
    if (g[i] == '"') break;
    v += g[i];
  }
  return v;
}

static Truth detect(const string& dir, const Scan& s) {
  // ---- 0: the user already told us -----------------------------------------
  // Discovery is a guess that is usually right; a declaration is not a guess.
  // It outranks every rung below, because the 34-of-66 projects on this machine
  // that discovery finds nothing in are exactly the ones whose owner knows the
  // command and had, until now, nowhere to put it.
  {
    const string declared = declared_check(dir);
    if (!declared.empty()) return {3, "declared", declared, ".rabadon/guard.json check"};
  }

  const string pkg = read_file(dir + "/package.json");
  const string mk  = read_file(dir + "/Makefile");

  // ---- 1: a real test suite ------------------------------------------------
  if (!pkg.empty()) {
    const string t = npm_script(pkg, "test");
    // the npm default stub is not a test suite; treating it as one would make
    // the net "green" on a repo that checks nothing
    if (!t.empty() && t.find("no test specified") == string::npos)
      return {3, "suite", "npm test --silent", "package.json scripts.test"};
  }
  if (!mk.empty() && make_has_target(mk, "test"))
    return {3, "suite", "make test", "Makefile test: target"};
  if (exists(dir + "/pytest.ini") || exists(dir + "/tests") || !s.testFiles.empty()) {
    if (s.py > 0) return {3, "suite", "python3 -m pytest -q", "python test files"};
  }
  if (exists(dir + "/Cargo.toml")) return {3, "suite", "cargo test --quiet", "Cargo.toml"};
  if (exists(dir + "/go.mod"))     return {3, "suite", "go test ./...", "go.mod"};

  // ---- 2: it still builds / typechecks ------------------------------------
  if (!pkg.empty()) {
    const string b = npm_script(pkg, "build");
    if (!b.empty()) return {2, "build", "npm run build --silent", "package.json scripts.build"};
  }
  if (exists(dir + "/tsconfig.json"))
    return {2, "build", "npx --no-install tsc --noEmit", "tsconfig.json"};
  if (exists(dir + "/CMakeLists.txt"))
    return {2, "build", "cmake --build build", "CMakeLists.txt"};
  if (!mk.empty() && (make_has_target(mk, "all") || make_has_target(mk, "build")))
    return {2, "build", make_has_target(mk, "all") ? "make all" : "make build", "Makefile"};
  if (exists(dir + "/Cargo.toml")) return {2, "build", "cargo build --quiet", "Cargo.toml"};
  if (exists(dir + "/go.mod"))     return {2, "build", "go build ./...", "go.mod"};

  // ---- 3: does every source file still parse ------------------------------
  // The weakest rung that can still go RED, and it needs nothing installed.
  // -f is not optional: without it compileall SKIPS a file whose cached .pyc
  // looks current, so the second run after a break returns 0 and the rung
  // silently stops being able to fail. Measured, not assumed — the test that
  // asserts "a rung that cannot fail is not a rung" caught exactly this.
  if (s.py > 0)  return {1, "syntax", "python3 -m compileall -q -f .", "python sources"};
  if (s.js > 0)  return {1, "syntax",
                         "find . -name '*.js' -not -path './node_modules/*' -print0 | xargs -0 -n1 node --check",
                         "javascript sources"};
  if (s.cpp > 0) return {1, "syntax", "", "c++ sources (no build file found)"};

  return {0, "none", "", "nothing runnable found"};
}

static string json_escape(const string& s) {
  string o;
  for (char c : s) {
    if (c == '"' || c == '\\') { o += '\\'; o += c; }
    else if (c == '\n') o += "\\n";
    else o += c;
  }
  return o;
}

static const char* kHelp =
  "rabadon-truth — what does THIS repo already know how to check?\n"
  "Walks the project and reports the strongest thing that can be RUN and can come\n"
  "back red. Nothing here calls a model; the rung is discovered from real files.\n"
  "\n"
  "  level 3 SUITE   the project's own test suite   (can fail for behaviour)\n"
  "  level 2 BUILD   compile / typecheck            (can fail for meaning)\n"
  "  level 1 SYNTAX  parse every source file        (can fail for form)\n"
  "  level 0 NONE    nothing runnable was found     (said out loud, never faked)\n"
  "\n"
  "usage: rabadon-truth [dir] [--json]\n"
  "\n"
  "  [dir]       the project to inspect (default: the current directory).\n"
  "  --json      machine-readable: level, kind, run, why, codeDirs, testFiles.\n"
  "  -h, --help  this screen.\n"
  "\n"
  "example:\n"
  "  rabadon-truth ~/src/myrepo --json\n";

int main(int argc, char** argv) {
  rb_help(argc, argv, kHelp);

  string dir = ".";
  bool asJson = false;
  for (int i = 1; i < argc; i++) {
    string a = argv[i];
    if (a == "--json") asJson = true;
    // an unknown flag used to become the DIRECTORY: `rabadon-truth -h` scanned a
    // repo named "-h", found nothing runnable, and reported level 0 NONE as if
    // that were a fact about your project.
    else if (rb_is_flag(a.c_str())) rb_unknown_flag("rabadon-truth", a.c_str());
    else dir = a;
  }
  while (dir.size() > 1 && dir.back() == '/') dir.pop_back();

  Scan s;
  load_guard_test_rx(dir, s);
  int budget = kMaxEntries;       // bounded walk: a huge repo must not stall a hook
  scan_into(dir, "", s, 0, budget);
  // A file called exactly `test.ts` is only a test file if the repo does it on
  // purpose. Three of them, in three different directories, is a convention;
  // one is a stray. date-fns has 253 in 253 directories and every one of them
  // was invisible; jinja has one, and locking it would have been an outage.
  {
    vector<string> dirsSeen;
    for (const string& c : s.stemCandidates) {
      size_t k = c.rfind('/');
      const string d = k == string::npos ? string(".") : c.substr(0, k);
      if (std::find(dirsSeen.begin(), dirsSeen.end(), d) == dirsSeen.end()) dirsSeen.push_back(d);
    }
    if (s.stemCandidates.size() >= 3 && dirsSeen.size() >= 3)
      for (const string& c : s.stemCandidates) {
        if (s.testFiles.size() >= kMaxTestFiles) { s.cappedList = true; break; }
        s.testFiles.push_back(c);
      }
  }
  Truth t = detect(dir, s);

  if (asJson) {
    string dirs;
    for (size_t i = 0; i < s.codeDirs.size() && i < 12; i++) {
      if (i) dirs += ",";
      dirs += "\"" + json_escape(s.codeDirs[i]) + "\"";
    }
    string tests;
    for (size_t i = 0; i < s.testFiles.size(); i++) {
      if (i) tests += ",";
      tests += "\"" + json_escape(s.testFiles[i]) + "\"";
    }
    string cap;
    { const string c = s.capped();
      size_t i = 0;
      while (i < c.size()) {
        size_t j = c.find(',', i);
        if (j == string::npos) j = c.size();
        if (!cap.empty()) cap += ",";
        cap += "\"" + c.substr(i, j - i) + "\"";
        i = j + 1;
      } }
    printf("{\"level\":%d,\"kind\":\"%s\",\"run\":\"%s\",\"why\":\"%s\","
           "\"codeFiles\":%d,\"codeDirs\":[%s],\"testFiles\":[%s],\"discoveryCapped\":[%s]}\n",
           t.level, t.kind.c_str(), json_escape(t.run).c_str(), json_escape(t.why).c_str(),
           s.total(), dirs.c_str(), tests.c_str(), cap.c_str());
  } else {
    const char* label = t.level == 3 ? "SUITE  (strong: real behaviour)"
                      : t.level == 2 ? "BUILD  (medium: it still compiles)"
                      : t.level == 1 ? "SYNTAX (weak: it still parses)"
                                     : "NONE   (nothing runnable — rabadon will say so, not pretend)";
    printf("%-28s  level %d  %s\n", dir.c_str(), t.level, label);
    if (!t.run.empty()) printf("    run: %s\n    via: %s\n", t.run.c_str(), t.why.c_str());
    printf("    %d code files in [", s.total());
    for (size_t i = 0; i < s.codeDirs.size() && i < 8; i++) printf("%s%s", i ? " " : "", s.codeDirs[i].c_str());
    printf("]%s\n", s.testFiles.empty() ? "" : (" · " + std::to_string(s.testFiles.size()) + " test file(s) to lock").c_str());
  }
  return t.level == 0 ? 1 : 0;
}
